### ISSUE TITLE
Showing this error

### ISSUE THREAD

**Issue by ankit2404** [divanov11/Django-2021#18]
Uncaught ReferenceError: hljs is not defined at HTMLDocument.<anonymous> (app.js:5:3)

**Comment by Kordianz** [comment]
In my code it that same :)

Not works button, and alert block is in left, but it's not roblem. This is DJANGO course not JS, in future I correct this in jquery;)

**Comment by ankit2404** [comment]
I know this is a Django course I want you to know and fix it so the person
who doesn't know javascript will not face any problems while learning from
your course. By the way, your course is awesome it helped a lot
Thanks
Ankit Mittal

**Comment by Kordianz** [comment]
Yes, I to love this course. I just starts account part, but in same time, create my first own projekt, little learn, next do myself,

**Comment by vklodik** [comment]
I have fixed the app.js code to bring back the notification block removal functionality:
```
document.addEventListener('DOMContentLoaded', function () {
  hljs.highlightAll();
});


let alertWrapper = document.querySelector('.alert')
let alertClose = document.querySelector('.alert__close')

if (alertWrapper) {
  alertClose.addEventListener('click', function () {
    document.getElementsByClassName('alert')[0].style.display = 'none'
  })
}
```

> Uncaught ReferenceError: hljs is not defined at HTMLDocument. (app.js:5:3)
